version: "3"

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - front-tier

  web:
    container_name: django
    restart: always
    build:
      context: ./web/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - web-volume:/code
    ports:
      - "801:8000"
    expose: 
      - "8000"
    networks:
      - front-tier
      - back-tier
    command: gunicorn webproject.wsgi:application -w 2 -b 0.0.0.0:8000 

  db:
    container_name: postgres
    restart: always
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - postgres-volume-backup:/backup
    networks:
      - back-tier
    expose:
      - "5432"

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    networks:
      - front-tier
    expose:
      - "6379"

networks:
  front-tier:
  back-tier:

volumes:
  web-volume:
  postgres-volume:
  postgres-volume-backup:

    