version: "3"

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile      
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "80:80"
    networks:
      - front-tier

  web:
    container_name: django
    restart: always
    build:
      context: ./web/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./web:/code
    ports:
      - "801:8000"
    expose: 
      - "8000"
    networks:
      - front-tier
      - back-tier
    command: gunicorn webproject.wsgi:application -w 2 -b 0.0.0.0:8000 

  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    env_file: .env
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
      - ./backups/postgresql:/backup
    networks:
      - back-tier
    expose:
      - "5432"

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    networks:
      - front-tier
    expose:
      - "6379"

networks:
  front-tier:
  back-tier:
    